/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts;

import java.util.Random;
/**
 *
 * @author ZAN
 */
public class RPC extends javax.swing.JFrame {

    /**
     * Creates new form RPC
     */
    public RPC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPlayer = new javax.swing.ButtonGroup();
        Title = new javax.swing.JPanel();
        lIcon1 = new javax.swing.JLabel();
        lTitle = new javax.swing.JLabel();
        lIcon2 = new javax.swing.JLabel();
        Player = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbRock = new javax.swing.JCheckBox();
        cbPaper = new javax.swing.JCheckBox();
        cbScissors = new javax.swing.JCheckBox();
        Comp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbRockc = new javax.swing.JCheckBox();
        cbPaperc = new javax.swing.JCheckBox();
        cbScissorsc = new javax.swing.JCheckBox();
        Result = new javax.swing.JPanel();
        lResult = new javax.swing.JLabel();
        tfResult = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(255, 204, 153));
        Title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 5));

        lIcon1.setIcon(new javax.swing.ImageIcon("A:\\.MINE\\CHAPTER 3\\Visual Programming\\img\\game.png")); // NOI18N
        Title.add(lIcon1);

        lTitle.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        lTitle.setForeground(new java.awt.Color(0, 0, 0));
        lTitle.setText("ROCK PAPER SCISSORS GAME");
        Title.add(lTitle);

        lIcon2.setIcon(new javax.swing.ImageIcon("A:\\.MINE\\CHAPTER 3\\Visual Programming\\img\\game.png")); // NOI18N
        Title.add(lIcon2);

        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 74));

        Player.setBackground(new java.awt.Color(204, 204, 204));
        Player.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 5));
        Player.setLayout(new java.awt.GridLayout(4, 1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PLAYER");
        Player.add(jLabel2);

        bgPlayer.add(cbRock);
        cbRock.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        cbRock.setForeground(new java.awt.Color(0, 0, 0));
        cbRock.setText("ROCK");
        cbRock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbRockMouseClicked(evt);
            }
        });
        Player.add(cbRock);

        bgPlayer.add(cbPaper);
        cbPaper.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        cbPaper.setForeground(new java.awt.Color(0, 0, 0));
        cbPaper.setText("PAPER");
        cbPaper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbPaperMouseClicked(evt);
            }
        });
        Player.add(cbPaper);

        bgPlayer.add(cbScissors);
        cbScissors.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        cbScissors.setForeground(new java.awt.Color(0, 0, 0));
        cbScissors.setText("SCISSORS");
        cbScissors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbScissorsMouseClicked(evt);
            }
        });
        Player.add(cbScissors);

        getContentPane().add(Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 390, 310));

        Comp.setBackground(new java.awt.Color(204, 204, 204));
        Comp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 5));
        Comp.setLayout(new java.awt.GridLayout(4, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COMPUTER");
        Comp.add(jLabel1);

        cbRockc.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        cbRockc.setForeground(new java.awt.Color(0, 0, 0));
        cbRockc.setText("ROCK");
        cbRockc.setEnabled(false);
        Comp.add(cbRockc);

        cbPaperc.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        cbPaperc.setForeground(new java.awt.Color(0, 0, 0));
        cbPaperc.setText("PAPER");
        cbPaperc.setEnabled(false);
        Comp.add(cbPaperc);

        cbScissorsc.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        cbScissorsc.setForeground(new java.awt.Color(0, 0, 0));
        cbScissorsc.setText("SCISSORS");
        cbScissorsc.setEnabled(false);
        Comp.add(cbScissorsc);

        getContentPane().add(Comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 380, 310));

        Result.setBackground(new java.awt.Color(204, 204, 204));
        Result.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 3));
        Result.setLayout(new java.awt.BorderLayout());

        lResult.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lResult.setForeground(new java.awt.Color(0, 0, 0));
        lResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lResult.setText("RESULT =");
        Result.add(lResult, java.awt.BorderLayout.PAGE_START);
        Result.add(tfResult, java.awt.BorderLayout.CENTER);

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        Result.add(btnExit, java.awt.BorderLayout.LINE_END);

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        Result.add(btnClear, java.awt.BorderLayout.LINE_START);

        getContentPane().add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 770, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
            cbRock.setSelected(false);
            cbScissors.setSelected(false);
            cbPaper.setSelected(false);
            cbRockc.setSelected(false);
            cbScissorsc.setSelected(false);
            cbPaperc.setSelected(false);
            tfResult.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void cbRockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbRockMouseClicked
        Random ran = new Random();
        
        int rancomp = ran.nextInt(3); 
        
        if(rancomp== 0){
            cbRockc.setSelected(true);
            cbPaperc.setSelected(false);
            cbScissorsc.setSelected(false);
        }else if(rancomp == 1){
            cbPaperc.setSelected(true);
            cbScissorsc.setSelected(false);
            cbRockc.setSelected(false);
        }else if(rancomp == 2){
            cbScissorsc.setSelected(true);
            cbRockc.setSelected(false);
            cbPaperc.setSelected(false);
        }
        
        if(cbRock.isSelected() && cbPaperc.isSelected()){
            tfResult.setText("KALAH !!!");
        }else if(cbRock.isSelected() && cbRockc.isSelected()){
            tfResult.setText("IMBANG !!!");
        }else if(cbRock.isSelected() && cbScissorsc.isSelected()){
            tfResult.setText("MENANG !!!");
        }
    }//GEN-LAST:event_cbRockMouseClicked

    private void cbPaperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbPaperMouseClicked
        Random ran = new Random();
        
        int rancomp = ran.nextInt(3); 
        
        if(rancomp== 0){
            cbRockc.setSelected(true);
            cbPaperc.setSelected(false);
            cbScissorsc.setSelected(false);
        }else if(rancomp == 1){
            cbPaperc.setSelected(true);
            cbScissorsc.setSelected(false);
            cbRockc.setSelected(false);
        }else if(rancomp == 2){
            cbScissorsc.setSelected(true);
            cbRockc.setSelected(false);
            cbPaperc.setSelected(false);
        }
        
        
        if(cbPaper.isSelected() && cbPaperc.isSelected()){
            tfResult.setText("IMBANG !!!");
        }else if(cbPaper.isSelected() && cbRockc.isSelected()){
            tfResult.setText("MENANG !!!");
        }else if(cbPaper.isSelected() && cbScissorsc.isSelected()){
            tfResult.setText("KALAH !!!");
        }
        
    }//GEN-LAST:event_cbPaperMouseClicked

    private void cbScissorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbScissorsMouseClicked
        Random ran = new Random();
        
        int rancomp = ran.nextInt(3); 
        
        if(rancomp== 0){
            cbRockc.setSelected(true);
            cbPaperc.setSelected(false);
            cbScissorsc.setSelected(false);
        }else if(rancomp == 1){
            cbPaperc.setSelected(true);
            cbScissorsc.setSelected(false);
            cbRockc.setSelected(false);
        }else if(rancomp == 2){
            cbScissorsc.setSelected(true);
            cbRockc.setSelected(false);
            cbPaperc.setSelected(false);
        }
        
        if(cbScissors.isSelected() && cbPaperc.isSelected()){
            tfResult.setText("MENANG !!!");
        }else if(cbScissors.isSelected() && cbRockc.isSelected()){
            tfResult.setText("KALAH !!!");
        }else if(cbScissors.isSelected() && cbScissorsc.isSelected()){
            tfResult.setText("IMBANG !!!");
        }
    }//GEN-LAST:event_cbScissorsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Comp;
    private javax.swing.JPanel Player;
    private javax.swing.JPanel Result;
    private javax.swing.JPanel Title;
    private javax.swing.ButtonGroup bgPlayer;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JCheckBox cbPaper;
    private javax.swing.JCheckBox cbPaperc;
    private javax.swing.JCheckBox cbRock;
    private javax.swing.JCheckBox cbRockc;
    private javax.swing.JCheckBox cbScissors;
    private javax.swing.JCheckBox cbScissorsc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lIcon1;
    private javax.swing.JLabel lIcon2;
    private javax.swing.JLabel lResult;
    private javax.swing.JLabel lTitle;
    private javax.swing.JTextField tfResult;
    // End of variables declaration//GEN-END:variables
}
